In [4]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent work nice',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 50


In [5]:
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[35, 47], [6, 21], [25, 45], [5, 21], [17, 21, 5], [8], [31, 45], [47, 6], [31, 21], [32, 25, 47, 6]]
[[35 47  0  0]
 [ 6 21  0  0]
 [25 45  0  0]
 [ 5 21  0  0]
 [17 21  5  0]
 [ 8  0  0  0]
 [31 45  0  0]
 [47  6  0  0]
 [31 21  0  0]
 [32 25 47  6]]


In [6]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_2 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [7]:
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=1)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

C:\Users\seeho\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/50
10/10 [==============================] - 0s 45ms/step - loss: 0.6852 - accuracy: 0.8000
Epoch 2/50
10/10 [==============================] - 0s 400us/step - loss: 0.6836 - accuracy: 0.8000
Epoch 3/50
10/10 [==============================] - 0s 199us/step - loss: 0.6820 - accuracy: 0.8000
Epoch 4/50
10/10 [==============================] - 0s 399us/step - loss: 0.6804 - accuracy: 0.9000
Epoch 5/50
10/10 [==============================] - 0s 300us/step - loss: 0.6788 - accuracy: 0.9000
Epoch 6/50
10/10 [==============================] - 0s 201us/step - loss: 0.6772 - accuracy: 0.9000
Epoch 7/50
10/10 [==============================] - 0s 304us/step - loss: 0.6756 - accuracy: 0.9000
Epoch 8/50
10/10 [==============================] - 0s 199us/step - loss: 0.6740 - accuracy: 0.9000
Epoch 9/50
10/10 [==============================] - 0s 300us/step - loss: 0.6724 - accuracy: 0.9000
Epoch 10/50
10/10 [==============================] - 0s 100us/step - loss: 0.6708 - accuracy: 0.9000
